export const mockData = {
    board: {
        id: '1',
        title: 'Board Title',
        description: 'Board Desc',
        type: 'public', // 'private',
        ownerIds: [],
        members: [
            {
                id: 1,
                name: 'Hoafn0730',
                avatar: 'https://avatars.githubusercontent.com/u/140341133?v=4',
            },
            {
                id: 2,
                name: 'Hoafn0730',
                avatar: '',
            },
            {
                id: 3,
                name: 'Hoafn0730',
                avatar: '',
            },
            {
                id: 4,
                name: 'Hoafn0730',
                avatar: 'https://avatars.githubusercontent.com/u/140341133?v=4',
            },
            {
                id: 5,
                name: 'Hoafn0730',
                avatar: 'https://avatars.githubusercontent.com/u/140341133?v=4',
            },
        ],
        columnOrderIds: ['column-id-01', 'column-id-02'],
        columns: [
            {
                id: 'column-id-01',
                boardId: 'board-id-01',
                title: 'To Do Column 01',
                cardOrderIds: [
                    'card-id-01',
                    'card-id-02',
                    'card-id-03',
                    'card-id-04',
                    'card-id-05',
                    'card-id-06',
                    'card-id-07',
                ],
                cards: [
                    {
                        id: 'card-id-01',
                        boardId: 'board-id-01',
                        columnId: 'column-id-01',
                        title: 'Title of card 01',
                        description: 'Markdown Syntax (sẽ ở khóa nâng cao nhé)',
                        image: 'https://trungquandev.com/wp-content/uploads/2022/07/fair-mern-stack-advanced-banner-trungquandev.jpg',
                        memberIds: ['test-user-id-01'],
                        comments: ['test comment 01', 'test comment 02'],
                        attachments: ['test attachment 01', 'test attachment 02', 'test attachment 03'],
                    },
                    {
                        id: 'card-id-02',
                        boardId: 'board-id-01',
                        columnId: 'column-id-01',
                        title: 'Title of card 02',
                        description: null,
                        image: null,
                        memberIds: [],
                        comments: [],
                        attachments: [],
                    },
                    {
                        id: 'card-id-03',
                        boardId: 'board-id-01',
                        columnId: 'column-id-01',
                        title: 'Title of card 03',
                        description: null,
                        image: null,
                        memberIds: [],
                        comments: [],
                        attachments: [],
                    },
                    {
                        id: 'card-id-04',
                        boardId: 'board-id-01',
                        columnId: 'column-id-01',
                        title: 'Title of card 04',
                        description: null,
                        image: null,
                        memberIds: [],
                        comments: [],
                        attachments: [],
                    },
                    {
                        id: 'card-id-05',
                        boardId: 'board-id-01',
                        columnId: 'column-id-01',
                        title: 'Title of card 05',
                        description: null,
                        image: null,
                        memberIds: [],
                        comments: [],
                        attachments: [],
                    },
                    {
                        id: 'card-id-06',
                        boardId: 'board-id-01',
                        columnId: 'column-id-01',
                        title: 'Title of card 06',
                        description: null,
                        image: null,
                        memberIds: [],
                        comments: [],
                        attachments: [],
                    },
                    {
                        id: 'card-id-07',
                        boardId: 'board-id-01',
                        columnId: 'column-id-01',
                        title: 'Title of card 07',
                        description: null,
                        image: null,
                        memberIds: [],
                        comments: [],
                        attachments: [],
                    },
                ],
            },
            {
                id: 'column-id-02',
                boardId: 'board-id-01',
                title: 'Inprogress Column 02',
                cardOrderIds: ['card-id-08', 'card-id-09', 'card-id-10'],
                cards: [
                    {
                        id: 'card-id-08',
                        boardId: 'board-id-01',
                        columnId: 'column-id-02',
                        title: 'Title of card 08',
                        description: null,
                        image: null,
                        memberIds: [],
                        comments: [],
                        attachments: [],
                    },
                    {
                        id: 'card-id-09',
                        boardId: 'board-id-01',
                        columnId: 'column-id-02',
                        title: 'Title of card 09',
                        description: null,
                        image: null,
                        memberIds: [],
                        comments: [],
                        attachments: [],
                    },
                    {
                        id: 'card-id-10',
                        boardId: 'board-id-01',
                        columnId: 'column-id-02',
                        title: 'Title of card 10',
                        description: null,
                        image: null,
                        memberIds: [],
                        comments: [],
                        attachments: [],
                    },
                ],
            },
        ],
    },
};
